version: "3.7"

services:
  app:
    image: ghcr.io/deutscher-pfadfinderbund/registration-page
    networks:
      - web
    restart: unless-stopped
    volumes:
      - ./persist/datomic:/code/.datomic
    environment:
      - PORT
      - ADMIN_USER
      - ADMIN_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dpb-jbfl.rule=Host(`jbfl.deutscher-pfadfinderbund.de`)"
      - "traefik.http.routers.dpb-jbfl.entrypoints=websecure"
      - "traefik.http.routers.dpb-jbfl.tls.certresolver=myresolver"
      - "traefik.http.services.dpb-jbfl.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
